spring:
  application:
    name: EmployeeManagementSystemApi
  datasource:
    url: jdbc:h2:mem:Employee
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2


app:
  jwt:
    secret: your_jwt_secret_key_here
    expiration: 36000000 # JWT expiration time in milliseconds (e.g., 1 hour)
